import type {
  ContractorNotification,
  ContractorProfile,
  MaintenanceJob,
  MessageThread,
} from '@/lib/types';
import { jobDetail, messageDetail, ROUTES } from '@/constants/routes';

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

export const DEMO_PROFILE: ContractorProfile = {
  id: 'contractor-demo-1',
  companyName: 'SwiftFix Plumbing Pty Ltd',
  abn: '12 345 678 901',
  contactPerson: 'Mike Thompson',
  mobile: '0412 345 678',
  email: 'mike@swiftfixplumbing.com.au',
  businessAddress: '45 Trade Street, Richmond VIC 3121',
  tradeCategory: 'Plumbing',
  licenceNumber: 'PL-2847591',
  licenceExpiry: '2027-03-15',
  verificationStatus: 'approved',
  bankDetailsOnFile: true,
};

export const DEMO_JOBS: MaintenanceJob[] = [
  {
    id: 'job-001',
    trackingNumber: 'MR-JOB001',
    propertyAddress: '12 Ocean View Dr, Bondi NSW 2026',
    issueSummary: 'Leaking kitchen tap',
    description:
      'Tenant reports constant dripping from kitchen mixer tap. Water pooling under sink. May need washer or cartridge replacement.',
    category: 'Plumbing',
    priority: 'medium',
    status: 'assigned',
    bucket: 'pending_jobs',
    submittedAt: hoursAgo(2),
    slaDueAt: hoursAgo(-4),
    tenant: { name: 'Sarah Chen', email: 'sarah.chen@email.com', phone: '0411 222 333' },
    agent: { name: 'James Wilson', email: 'james@crossub.com', phone: '0412 999 888' },
    crossubContact: { name: 'CROSSUB Maintenance', email: 'maintenance@crossub.com' },
    photos: ['/demo/leak-1.jpg', '/demo/leak-2.jpg'],
    completionEvidenceUploaded: false,
    tenantConfirmed: false,
    invoiceUploaded: false,
    timeline: [
      {
        id: 't1',
        at: hoursAgo(2),
        actor: 'System',
        actorRole: 'system',
        title: 'Job assigned to SwiftFix Plumbing',
        source: 'system',
      },
    ],
    source: 'demo',
  },
  {
    id: 'job-002',
    trackingNumber: 'MR-JOB002',
    propertyAddress: '88 Park Lane, South Yarra VIC 3141',
    issueSummary: 'Blocked bathroom drain',
    description:
      'Slow draining shower. Tenant tried drain cleaner without success. Possible hair/blockage in trap.',
    category: 'Plumbing',
    priority: 'high',
    status: 'awaiting_quotation_approval',
    bucket: 'awaiting_quotation_approval',
    submittedAt: daysAgo(2),
    tenant: { name: 'David Park', phone: '0423 456 789' },
    agent: { name: 'Emma Roberts', email: 'emma@crossub.com' },
    crossubContact: { name: 'CROSSUB Maintenance', email: 'maintenance@crossub.com' },
    photos: ['/demo/drain-1.jpg'],
    contractorResponse: 'accepted',
    quotation: {
      id: 'q-002',
      jobId: 'job-002',
      labourCost: 180,
      materialCost: 45,
      callOutFee: 95,
      totalAmount: 320,
      scope: 'Inspect and clear bathroom drain. Replace trap washer if worn.',
      estimatedCompletion: '2026-06-05',
      status: 'submitted',
      submittedAt: daysAgo(1),
    },
    completionEvidenceUploaded: false,
    tenantConfirmed: false,
    invoiceUploaded: false,
    timeline: [
      { id: 't2a', at: daysAgo(2), actor: 'Mike Thompson', actorRole: 'contractor', title: 'Job accepted', source: 'app' },
      { id: 't2b', at: daysAgo(1), actor: 'Mike Thompson', actorRole: 'contractor', title: 'Quotation submitted — $320.00', source: 'app' },
    ],
    source: 'demo',
  },
  {
    id: 'job-003',
    trackingNumber: 'MR-JOB003',
    propertyAddress: '5 Elm Court, Fitzroy VIC 3065',
    issueSummary: 'Hot water system not heating',
    description: 'No hot water since yesterday. Gas instantaneous system — pilot may be out or thermostat fault.',
    category: 'Plumbing',
    priority: 'critical',
    status: 'approved',
    bucket: 'approved_jobs',
    submittedAt: daysAgo(3),
    tenant: { name: 'Lisa Nguyen', phone: '0434 567 890' },
    agent: { name: 'James Wilson', email: 'james@crossub.com' },
    crossubContact: { name: 'CROSSUB Maintenance', email: 'maintenance@crossub.com' },
    photos: [],
    contractorResponse: 'accepted',
    quotation: {
      id: 'q-003',
      jobId: 'job-003',
      labourCost: 350,
      materialCost: 120,
      totalAmount: 470,
      scope: 'Diagnose and repair hot water system. Replace thermostat if required.',
      estimatedCompletion: '2026-06-04',
      status: 'approved',
      submittedAt: daysAgo(2),
    },
    appointmentAt: '2026-06-04T09:00:00',
    accessNotes: 'Tenant works from home — available all day',
    completionEvidenceUploaded: false,
    tenantConfirmed: false,
    invoiceUploaded: false,
    timeline: [
      { id: 't3a', at: daysAgo(3), actor: 'Mike Thompson', actorRole: 'contractor', title: 'Job accepted', source: 'app' },
      { id: 't3b', at: daysAgo(2), actor: 'Mike Thompson', actorRole: 'contractor', title: 'Quotation submitted', source: 'app' },
      { id: 't3c', at: daysAgo(1), actor: 'Agent', actorRole: 'agent', title: 'Quotation approved', source: 'app' },
    ],
    source: 'demo',
  },
  {
    id: 'job-004',
    trackingNumber: 'MR-JOB004',
    propertyAddress: '22 River Rd, Hawthorn VIC 3122',
    issueSummary: 'Toilet cistern running continuously',
    description: 'Cistern does not stop filling. Likely inlet valve or flush mechanism issue.',
    category: 'Plumbing',
    priority: 'medium',
    status: 'in_progress',
    bucket: 'in_progress',
    submittedAt: daysAgo(5),
    tenant: { name: 'Tom Baker', phone: '0445 678 901' },
    agent: { name: 'Emma Roberts', email: 'emma@crossub.com' },
    crossubContact: { name: 'CROSSUB Maintenance', email: 'maintenance@crossub.com' },
    photos: [],
    contractorResponse: 'accepted',
    quotation: {
      id: 'q-004',
      jobId: 'job-004',
      labourCost: 150,
      materialCost: 85,
      totalAmount: 235,
      scope: 'Replace cistern inlet valve and adjust flush mechanism.',
      estimatedCompletion: '2026-06-03',
      status: 'approved',
      submittedAt: daysAgo(4),
    },
    appointmentAt: '2026-06-03T14:00:00',
    completionEvidenceUploaded: false,
    tenantConfirmed: false,
    invoiceUploaded: false,
    timeline: [
      { id: 't4a', at: daysAgo(5), actor: 'Mike Thompson', actorRole: 'contractor', title: 'Job accepted', source: 'app' },
      { id: 't4b', at: daysAgo(4), actor: 'Agent', actorRole: 'agent', title: 'Quotation approved', source: 'app' },
      { id: 't4c', at: hoursAgo(6), actor: 'Mike Thompson', actorRole: 'contractor', title: 'Work started on site', source: 'app' },
    ],
    source: 'demo',
  },
  {
    id: 'job-005',
    trackingNumber: 'MR-JOB005',
    propertyAddress: '101 Collins St, Melbourne VIC 3000',
    issueSummary: 'Burst pipe under laundry sink',
    description: 'Emergency repair completed. Pipe replaced and tested.',
    category: 'Plumbing',
    priority: 'critical',
    status: 'awaiting_tenant_confirmation',
    bucket: 'awaiting_tenant_confirmation',
    submittedAt: daysAgo(7),
    tenant: { name: 'Anna Kowalski', phone: '0456 789 012' },
    agent: { name: 'James Wilson', email: 'james@crossub.com' },
    crossubContact: { name: 'CROSSUB Maintenance', email: 'maintenance@crossub.com' },
    photos: [],
    contractorResponse: 'accepted',
    quotation: {
      id: 'q-005',
      jobId: 'job-005',
      labourCost: 280,
      materialCost: 95,
      totalAmount: 375,
      scope: 'Emergency pipe repair under laundry sink.',
      estimatedCompletion: '2026-05-30',
      status: 'approved',
      submittedAt: daysAgo(6),
    },
    completionEvidenceUploaded: true,
    tenantConfirmed: false,
    invoiceUploaded: false,
    timeline: [
      { id: 't5a', at: daysAgo(1), actor: 'Mike Thompson', actorRole: 'contractor', title: 'Work completed — evidence uploaded', source: 'app' },
    ],
    source: 'demo',
  },
  {
    id: 'job-006',
    trackingNumber: 'MR-JOB006',
    propertyAddress: '7 Garden Ave, St Kilda VIC 3182',
    issueSummary: 'Dishwasher connection leak',
    description: 'Repair completed and tenant confirmed.',
    category: 'Plumbing',
    priority: 'low',
    status: 'invoice_submitted',
    bucket: 'pending_payment',
    submittedAt: daysAgo(14),
    tenant: { name: 'Chris Lee', phone: '0467 890 123' },
    agent: { name: 'Emma Roberts', email: 'emma@crossub.com' },
    crossubContact: { name: 'CROSSUB Maintenance', email: 'maintenance@crossub.com' },
    photos: [],
    contractorResponse: 'accepted',
    quotation: {
      id: 'q-006',
      jobId: 'job-006',
      labourCost: 120,
      materialCost: 35,
      totalAmount: 155,
      scope: 'Reseal dishwasher connection and replace hose clamp.',
      estimatedCompletion: '2026-05-20',
      status: 'approved',
      submittedAt: daysAgo(12),
    },
    completionEvidenceUploaded: true,
    tenantConfirmed: true,
    invoiceUploaded: true,
    paymentStatus: 'pending_payment',
    timeline: [
      { id: 't6a', at: daysAgo(3), actor: 'Mike Thompson', actorRole: 'contractor', title: 'Invoice submitted — $155.00', source: 'app' },
    ],
    source: 'demo',
  },
  {
    id: 'job-007',
    trackingNumber: 'MR-JOB007',
    propertyAddress: '3 Lake View, Carlton VIC 3053',
    issueSummary: 'Shower head replacement',
    description: 'Old shower head replaced with water-efficient model.',
    category: 'Plumbing',
    priority: 'low',
    status: 'paid',
    bucket: 'paid_jobs',
    submittedAt: daysAgo(30),
    tenant: { name: 'Priya Sharma', phone: '0478 901 234' },
    agent: { name: 'James Wilson', email: 'james@crossub.com' },
    crossubContact: { name: 'CROSSUB Maintenance', email: 'maintenance@crossub.com' },
    photos: [],
    contractorResponse: 'accepted',
    quotation: {
      id: 'q-007',
      jobId: 'job-007',
      labourCost: 80,
      materialCost: 65,
      totalAmount: 145,
      scope: 'Replace shower head with approved model.',
      estimatedCompletion: '2026-05-01',
      status: 'approved',
      submittedAt: daysAgo(28),
    },
    completionEvidenceUploaded: true,
    tenantConfirmed: true,
    invoiceUploaded: true,
    paymentStatus: 'payment_completed',
    paymentReference: 'PAY-20260515-8842',
    paidAt: daysAgo(10),
    timeline: [
      { id: 't7a', at: daysAgo(10), actor: 'CROSSUB', actorRole: 'crossub', title: 'Payment completed — PAY-20260515-8842', source: 'system' },
    ],
    source: 'demo',
  },
];

export const DEMO_MESSAGES: MessageThread[] = [
  {
    id: 'msg-001',
    jobId: 'job-003',
    jobTrackingNumber: 'MR-JOB003',
    propertyAddress: '5 Elm Court, Fitzroy VIC 3065',
    subject: 'Hot water — access arrangement',
    participants: ['Mike Thompson', 'Lisa Nguyen', 'CROSSUB Maintenance'],
    lastMessage: 'I can be home all day Thursday for the visit.',
    lastAt: hoursAgo(3),
    unread: 1,
    channel: 'app',
    messages: [
      {
        id: 'm1',
        at: daysAgo(1),
        from: 'Mike Thompson',
        fromRole: 'contractor',
        body: 'Hi Lisa, I have approval to attend. Does Thursday 9am work for access?',
        channel: 'app',
      },
      {
        id: 'm2',
        at: hoursAgo(3),
        from: 'Lisa Nguyen',
        fromRole: 'tenant',
        body: 'I can be home all day Thursday for the visit.',
        channel: 'app',
      },
    ],
  },
  {
    id: 'msg-002',
    jobId: 'job-002',
    jobTrackingNumber: 'MR-JOB002',
    propertyAddress: '88 Park Lane, South Yarra VIC 3141',
    subject: 'Drain blockage — additional photos',
    participants: ['Mike Thompson', 'David Park'],
    lastMessage: 'Uploaded two more photos of the drain.',
    lastAt: daysAgo(1),
    unread: 0,
    channel: 'app',
    messages: [
      {
        id: 'm3',
        at: daysAgo(2),
        from: 'Mike Thompson',
        fromRole: 'contractor',
        body: 'Could you send a close-up of the drain grate? Helps confirm if trap access is needed.',
        channel: 'app',
      },
      {
        id: 'm4',
        at: daysAgo(1),
        from: 'David Park',
        fromRole: 'tenant',
        body: 'Uploaded two more photos of the drain.',
        channel: 'app',
      },
    ],
  },
];

export const DEMO_NOTIFICATIONS: ContractorNotification[] = [
  {
    id: 'n-001',
    type: 'job_assigned',
    title: 'New job assigned',
    body: 'Leaking kitchen tap at 12 Ocean View Dr — respond within 4 hours.',
    jobTrackingNumber: 'MR-JOB001',
    at: hoursAgo(2),
    read: false,
    href: jobDetail('job-001'),
  },
  {
    id: 'n-002',
    type: 'quote_update',
    title: 'Quotation pending approval',
    body: 'Your quote for MR-JOB002 is awaiting agent approval.',
    jobTrackingNumber: 'MR-JOB002',
    at: daysAgo(1),
    read: true,
    href: jobDetail('job-002'),
  },
  {
    id: 'n-003',
    type: 'payment',
    title: 'Payment completed',
    body: 'Invoice for MR-JOB007 paid — reference PAY-20260515-8842.',
    jobTrackingNumber: 'MR-JOB007',
    at: daysAgo(10),
    read: true,
    href: jobDetail('job-007'),
  },
];

export const DASHBOARD_BUCKETS = [
  { bucket: 'pending_jobs' as const, label: 'Pending Jobs', href: `${ROUTES.JOBS}?bucket=pending_jobs`, tone: 'action' as const },
  { bucket: 'awaiting_quotation_approval' as const, label: 'Awaiting Quote Approval', href: `${ROUTES.JOBS}?bucket=awaiting_quotation_approval`, tone: 'warning' as const },
  { bucket: 'approved_jobs' as const, label: 'Approved Jobs', href: `${ROUTES.JOBS}?bucket=approved_jobs`, tone: 'default' as const },
  { bucket: 'in_progress' as const, label: 'In Progress', href: `${ROUTES.JOBS}?bucket=in_progress`, tone: 'default' as const },
  { bucket: 'awaiting_tenant_confirmation' as const, label: 'Awaiting Tenant Confirmation', href: `${ROUTES.JOBS}?bucket=awaiting_tenant_confirmation`, tone: 'warning' as const },
  { bucket: 'pending_payment' as const, label: 'Pending Payment', href: `${ROUTES.JOBS}?bucket=pending_payment`, tone: 'default' as const },
  { bucket: 'paid_jobs' as const, label: 'Paid Jobs', href: `${ROUTES.JOBS}?bucket=paid_jobs`, tone: 'default' as const },
];

export function countByBucket(jobs: MaintenanceJob[]) {
  return DASHBOARD_BUCKETS.map(({ bucket, label, href, tone }) => ({
    bucket,
    label,
    href,
    tone,
    count: jobs.filter((j) => j.bucket === bucket).length,
  }));
}

export { messageDetail };
